export default {
  MUSIC_RUNNING: 'ZeaMusic is running on PORT',
  SUCCESS: 'success',
  SUCCESS_RESPONSE: 'Request was successfully processed',
  FAIL: 'fail',
  WELCOME: 'Thanks for dropping by, you are at ZeaMusic',
  INVALID_CREDENTIALS: 'Incorrect login details',
  LOGIN_USER_SUCCESSFULLY: 'Login successful',
  UNAVAILABLE_TOKEN: 'You need to be signed in',
  MODULE_ERROR_STATUS: 'MODULE_PROCESS_BROKE',
  MODULE_ERROR: 'A module error occurred',
  USER_SIGNUP_SUCCESS:
    'Account created successfully',
  DB_ERROR_STATUS: 'DB_PROCESS_FAILED',
  DB_ERROR: 'A database error occurred, either in postgres',
  INVALID_PERMISSION: 'Permission denied. Invalid credentials provided',
  FORBIDDEN: 'Access forbidden. You do not have the required access.',
  USER_SIGNUP_ERROR: 'Sign up failed. It is not you, it is us.',
  ARTIST_SIGNUP_ERROR: 'Sign up failed. It is not you, it is us.',
  ARTIST_SIGNUP_ERROR_STATUS: 'ARTIST_SIGNUP_ERROR',
  USER_SIGNUP_ERROR_STATUS: 'USER_SIGNUP_ERROR',
  USER_ALREADY_EXIST: 'USER exists already',
  ALBUM_NOT_FOUND: 'Album does not exist',
  USERNAME_ALREADY_EXIST: 'USERNAME exists already',
  USER_NOT_VERIFIED: 'Only verified accounts can make request',
  ALBUM_EXIST_VERIFICATION_FAIL: 'ALBUM_EXIST_VERIFICATION_FAIL',
  USER_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL:
    'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL_MSG:
    'Login failed. It is not you, it is us.',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  INVALID_EMAIL: 'This email does not exist, please enter a registered email',
  USER_PASSWORD_RESET_FAIL_CAP: 'USER_PASSWORD_RESET_FAIL',
  USER_PASSWORD_RESET_FAIL: 'User Password reset failed to update',
  USER_NOT_FOUND: 'User not found',
  INVALID_USER_ID: 'Invalid user id',
  ERROR_VERIFYING_USER: 'ERROR VERIFYING USER',
  ERROR_VERIFYING_USER_MSG: 'Error trying to verify user. It is not you, it is us.',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  ACCESS_REVOKED: 'ACCESS REVOKED',
  AUTH_REQUIRED: 'Access denied,a valid access token is required',
  PARAM_ABSENT: (schema) => `Please provide a valid ${schema}`,
  USER_EXIST_VERIFICATION_FAIL_MSG:
  'Error trying to fetch user. It is not you, it is us.',
  RESOURCE_EXISTS: (resource) => `${resource} exists already.`,
  RESOURCE_NOT_EXISTS: (resource) => `${resource} does not exist`,
  RESOURCE_FETCH_SUCCESS: (resource) => `${resource} fetched successfully`,
  RESOURCE_FETCH_ERROR: (resource) => `could not fetch ${resource}`,
  RESOURCE_EXISTS_VERIFICATION_FAIL: (resource) => `${resource}_EXIST_VERIFICATION_FAIL`,
  RESOURCE_EXISTS_VERIFICATION_FAIL_MSG: (resource) => `${resource} verification failed. It is not you, it is us.`,
  RESOURCE_CREATE_ERROR_STATUS: (resource) => `${resource}_CREATE_ERROR`,
  RESOURCE_CREATE_SUCCESS: (resource) => `${resource} created successfully`,
  RESOURCE_UPLOAD_ERROR_STATUS: (resource) => `${resource}_UPLOAD_ERROR`,
  RESOURCE_CREATE_ERROR_MSG: (resource) => `Error trying to create ${resource}. It is not you, it is us.`,
  RESOURCE_UPLOAD_ERROR_MSG: (resource) => `${resource} upload failed. It is not you, it is us.`,
  RESOURCE_UPLOAD_SUCCESS: (resource) => `${resource} uploaded successfully`,
  RESOURCE_UPDATE_SUCCESS: (resource) => `${resource} updated successfully`,
  RESOURCE_UPDATE_ERROR_MSG: (resource) => `Error trying to update ${resource}. It is not you, it is us.`,
  RESOURCE_UPDATE_ERROR_STATUS: (resource) => `${resource}_UPDATE_ERROR`
}
